spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://zemoga-test-db.crhpedy9xxto.us-east-1.rds.amazonaws.com:3306/portfolioDB
    username: zemoga_test_db
    password: Zem0ga.101
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: KRy7l0v8wex3w8Sy5zThai3Ea
            client-authentication-method: X2eBm0Y21kYEuR74W3Frqc2JVIizOj8Q1EVGatDsEVVEJo0ucu
            authorization-grant-type: authorization_code

twitter:
  oauth:
    consumerKey: KRy7l0v8wex3w8Sy5zThai3Ea
    consumerSecret: X2eBm0Y21kYEuR74W3Frqc2JVIizOj8Q1EVGatDsEVVEJo0ucu
    accessToken: 1220032047516921859-otvXjhExyUTZ5GLxssc9h5ORqtPZja
    accessTokenSecret: tmJKqM4ORfQW6CH7wIVV8uKNpmSEmeFAP8lYwGb19uYjj
